### ISSUE TITLE
Typos e valores faltando nas modelagens 2.1.3, 2.1.3 Pro e 3.0

### ISSUE THREAD

**Issue by jpesperidiao** [dsgoficial/modelagens#1]
## 2.1.3 Pro:

- Meando abandonado -> Meandro abandonado
- codelist "Subestação de energia" faltando em tipo_elemento_infraestrutura
- codelist "Subestação de transmissão de energia" faltando em tipo_elemento_infraestrutura
- codelist "Subestação de distribuição de energia" faltando em tipo_elemento_infraestrutura

## 2.1.3:

- "Postdam 1930" -> "Potsdam 1930" no referencialgrav
- codelist "Subestação de energia" faltando Ponto_Trecho_Energia tipo

## 3.0:

- Existe algo relativo ao codelist da classe `Deposito_Geral` (atributo `Tipo_Dep_Geral`) registrado no issue [#436 do DSGTools](https://github.com/dsgoficial/DsgTools/issues/436). Eu não entendi bem, mas acho que antes não existia o codelist (1, "Tanque") e, por isso, essa restrição não era checada (agora é por meio de FK, inclusive verifiquei que já está na SQL).

**Comment by dinizime** [comment]
- EDGV 2.1.3 Pro: Sobre subestação de energia elas foram removidas pois são complexos na EDGV 2.1.3. A aquisição correta é o uso do valor Grupo Transformadores.

- EDGV 2.13: Ponto_Trecho_Energia tem os seguintes valores válidos: Desconhecido, Estação Geradora de Energia, Subestação de transmissão, Subestação de distribuição, Ponto de Ramificação.

O restante foi corrigido.
